# Generated by Django 4.2.5 on 2023-12-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName',models.CharField(max_length=100)),
                ('Email',models.CharField(max_length=100)),
                ('PanCard',models.CharField(max_length=10)),
                ('AdhaarCard',models.IntegerField(default=0))
            ],
        ),
    ]
