# Generated by Django 4.2.5 on 2024-04-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0003_rename_pancard_userdata_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='Gender',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
