# Generated by Django 4.2.5 on 2024-04-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0004_userdata_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='AdhaarCard',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='Email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='Gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='Mobile',
            field=models.CharField(max_length=15),
        ),
    ]
